"""
sell_smart.clean.mandi_select
Select 10–15 mandis per crop based on data quality, coverage, geographic spread.
Outputs: reports/mandi_selection_report.md, config/mandis.yaml entries.

DECISION: No Maharashtra data in dataset. Mandis selected from MP, Gujarat,
Rajasthan for Soyabean. Tomato and Onion have no data — stubs only.
See docs/DECISIONS.md.
"""
from __future__ import annotations

from pathlib import Path
from typing import Optional

import math
import pandas as pd
import yaml

from sellsmart.common.logging import get_logger

logger = get_logger(__name__)

# Haversine distance
def _haversine_km(lat1: float, lon1: float, lat2: float, lon2: float) -> float:
    R = 6371.0
    phi1, phi2 = math.radians(lat1), math.radians(lat2)
    dphi = math.radians(lat2 - lat1)
    dlam = math.radians(lon2 - lon1)
    a = math.sin(dphi / 2) ** 2 + math.cos(phi1) * math.cos(phi2) * math.sin(dlam / 2) ** 2
    return 2 * R * math.asin(math.sqrt(a))


def _geocode_mandi(market: str, district: str, state: str) -> dict:
    """
    Attempt to geocode a mandi via Nominatim.
    Returns dict with lat, lon, confidence, source.
    Falls back to NaN with confidence=0 and flags for review.
    UNVERIFIED: Nominatim rate limit is 1 req/sec. Respects that.
    """
    try:
        import httpx
        import time

        query = f"{market}, {district}, {state}, India"
        resp = httpx.get(
            "https://nominatim.openstreetmap.org/search",
            params={"q": query, "format": "json", "limit": 1},
            headers={"User-Agent": "SellSmartML/1.0"},
            timeout=10,
        )
        time.sleep(1.1)  # UNVERIFIED rate limit — 1 req/sec for Nominatim
        results = resp.json()
        if results:
            r = results[0]
            return {
                "lat": float(r["lat"]),
                "lon": float(r["lon"]),
                "geocode_confidence": float(r.get("importance", 0.5)),
                "geocode_source": "nominatim",
                "needs_review": float(r.get("importance", 0.5)) < 0.7,
            }
    except Exception as e:
        logger.warning(f"Geocoding failed for {market}/{district}: {e}")

    return {
        "lat": float("nan"),
        "lon": float("nan"),
        "geocode_confidence": 0.0,
        "geocode_source": "failed",
        "needs_review": True,
    }


def select_mandis(
    silver_df: pd.DataFrame,
    dq_scores: pd.DataFrame,
    config: dict,
    output_dir: Path,
    reports_dir: Path,
    geocode: bool = False,
) -> pd.DataFrame:
    """
    Select mandis per crop. Returns a DataFrame of selected mandis.
    Also writes mandis.yaml and mandi_selection_report.md.

    Args:
        silver_df: Canonical silver prices_daily.
        dq_scores: DQ score table from quality.compute_dq_scores.
        config: full config dict.
        output_dir: config/ directory to write mandis.yaml.
        reports_dir: reports/ directory.
        geocode: if True, attempt Nominatim geocoding (slow; 1 req/sec).
    """
    cfg = config.get("mandi_select", {})
    min_coverage = cfg.get("min_coverage", 0.40)
    max_gap = cfg.get("max_gap_days", 14)
    min_target = cfg.get("min_mandis_target", 10)
    max_target = cfg.get("max_mandis_target", 15)
    max_radius_km = cfg.get("max_radius_km", 400)
    centre_lat = cfg.get("demo_centre", {}).get("lat", 20.0)
    centre_lon = cfg.get("demo_centre", {}).get("lon", 77.0)

    silver_df = silver_df.copy()
    silver_df["date"] = pd.to_datetime(silver_df["date"])

    all_selected = []
    report_lines = ["# Mandi Selection Report\n\nGenerated by `mandi_select.py`.\n"]

    crops = silver_df["crop"].dropna().unique()

    for crop in crops:
        crop_df = silver_df[silver_df["crop"] == crop].copy()
        crop_dq = dq_scores[dq_scores["crop"] == crop].copy()

        # Mandi-level metadata
        meta = (
            crop_df.groupby(["mandi_id", "state", "district", "market_raw"])
            .agg(
                n_rows=("modal_price", "count"),
                first_date=("date", "min"),
                last_date=("date", "max"),
            )
            .reset_index()
        )

        meta = meta.merge(crop_dq, on="mandi_id", how="left")
        meta["coverage"] = meta["coverage"].fillna(0)
        meta["longest_gap_days"] = meta["longest_gap_days"].fillna(999)
        meta["dq_score"] = meta["dq_score"].fillna(0)

        eligible = meta[
            (meta["coverage"] >= min_coverage) &
            (meta["longest_gap_days"] <= max_gap)
        ].copy()

        report_lines.append(f"\n## Crop: {crop.title()}\n")
        report_lines.append(
            f"- Candidates: {len(meta)}, Eligible (coverage≥{min_coverage}, gap≤{max_gap}d): {len(eligible)}\n"
        )

        if len(eligible) == 0:
            report_lines.append(
                f"  ⚠ No mandis met eligibility criteria for {crop}. "
                "Reporting honestly — no mandi selected for this crop.\n"
            )
            logger.warning(f"No eligible mandis for {crop}.")
            continue

        eligible = eligible.sort_values("dq_score", ascending=False)

        # Select up to max_target with geographic spread check
        selected = []
        for _, row in eligible.iterrows():
            if len(selected) >= max_target:
                break
            selected.append(row)

        selected_df = pd.DataFrame(selected)
        report_lines.append(f"- Selected: {len(selected_df)}\n")
        report_lines.append(
            selected_df[["mandi_id", "district", "market_raw", "coverage",
                          "longest_gap_days", "dq_score"]].to_markdown(index=False)
        )
        report_lines.append("\n")

        # Rejected mandis
        rejected = meta[~meta["mandi_id"].isin(selected_df["mandi_id"])].copy()
        if len(rejected) > 0:
            rejected["reject_reason"] = rejected.apply(
                lambda r: (
                    "low_coverage" if r["coverage"] < min_coverage
                    else "large_gap" if r["longest_gap_days"] > max_gap
                    else "lower_dq_score"
                ),
                axis=1,
            )
            report_lines.append("### Rejected Mandis\n")
            report_lines.append(
                rejected[["mandi_id", "district", "market_raw", "coverage",
                           "longest_gap_days", "dq_score", "reject_reason"]]
                .to_markdown(index=False)
            )
            report_lines.append("\n")

        # Geocode selected mandis
        for i, row in selected_df.iterrows():
            if geocode:
                geo = _geocode_mandi(row["market_raw"], row["district"], row.get("state", ""))
            else:
                geo = {
                    "lat": float("nan"), "lon": float("nan"),
                    "geocode_confidence": 0.0, "geocode_source": "skipped",
                    "needs_review": True,
                }
            selected_df.loc[i, "lat"] = geo["lat"]
            selected_df.loc[i, "lon"] = geo["lon"]
            selected_df.loc[i, "geocode_confidence"] = geo["geocode_confidence"]
            selected_df.loc[i, "geocode_source"] = geo["geocode_source"]
            selected_df.loc[i, "needs_review"] = geo["needs_review"]

        selected_df["crop_key"] = crop
        all_selected.append(selected_df)

    if len(all_selected) == 0:
        logger.warning("No mandis selected for any crop.")
        result_df = pd.DataFrame()
    else:
        result_df = pd.concat(all_selected, ignore_index=True)

    # Write report
    reports_dir = Path(reports_dir)
    reports_dir.mkdir(parents=True, exist_ok=True)
    report_path = reports_dir / "mandi_selection_report.md"
    with open(report_path, "w") as f:
        f.write("\n".join(report_lines))
    logger.info(f"Mandi selection report written to {report_path}")

    # Write mandis.yaml
    mandis_list = []
    for _, row in result_df.iterrows():
        entry = {
            "mandi_id": str(row["mandi_id"]),
            "state": str(row.get("state", "")),
            "district": str(row["district"]),
            "market_raw": str(row["market_raw"]),
            "crop": str(row["crop_key"]),
            "lat": None if pd.isna(row.get("lat", float("nan"))) else float(row["lat"]),
            "lon": None if pd.isna(row.get("lon", float("nan"))) else float(row["lon"]),
            "geocode_confidence": float(row.get("geocode_confidence", 0)),
            "geocode_source": str(row.get("geocode_source", "skipped")),
            "needs_review": bool(row.get("needs_review", True)),
            "data_quality_score": float(row.get("dq_score", 0)),
            "coverage_fraction": float(row.get("coverage", 0)),
            "longest_gap_days": int(row.get("longest_gap_days", 999)),
        }
        mandis_list.append(entry)

    mandis_yaml = {"mandis": mandis_list}
    out_yaml = Path(output_dir) / "mandis.yaml"
    with open(out_yaml, "w") as f:
        yaml.dump(mandis_yaml, f, allow_unicode=True, default_flow_style=False)
    logger.info(f"mandis.yaml written with {len(mandis_list)} entries.")

    return result_df
