import React, { useEffect, useMemo, useState } from 'react';
import { AlertCircle, Bell, ChevronRight, CircleHelp, CloudOff, Mic, Send, ShieldCheck, Sparkles, TrendingUp } from 'lucide-react';
import { Language, ScreenType, ChatMessage } from '../types';
import { api } from '../api/adapter';
import { ChatReply, NotificationEvent } from '../contracts/schemas';
import { mockWaitWithTrigger } from '../mocks/fixtures';
import { MandiMap } from '../components/MandiMap';

interface ChatsScreenProps { language: Language; onNavigate: (screen: ScreenType) => void; }
const money = (value: number | null | undefined) => value == null ? '—' : `₹${value.toLocaleString('en-IN')}`;
const statusLabel: Record<string, Record<Language, string>> = {
  ACCEPT_OFFER: { en: 'Accept offer', hi: 'ऑफर स्वीकार करें', mr: 'ऑफर स्वीकारा' },
  SWITCH_MARKET_NOW: { en: 'Switch market', hi: 'बाजार बदलें', mr: 'बाजार बदला' },
  WAIT_WITH_TRIGGER: { en: 'Wait with trigger', hi: 'संकेत तक रुकें', mr: 'संकेत मिळेपर्यंत थांबा' },
  SELL_NOW_NEAREST: { en: 'Sell now', hi: 'अभी बेचें', mr: 'आता विका' },
  NO_CONFIDENT_ADVICE: { en: 'Advice paused', hi: 'सलाह रुकी है', mr: 'सल्ला थांबवला' },
};

const labels = (language: Language) => language === 'mr' ? {
  advice: 'सल्ला कार्ड', typical: 'साधारण निव्वळ रक्कम', likely: 'शक्य श्रेणी', confidence: 'विश्वास', measured: 'आज जवळच्या बाजारात विक्रीच्या तुलनेत', modal: 'मंडीतील साधारण भाव हा संदर्भ आहे; मिळणारी पक्की रक्कम नाही.', breakdown: 'निव्वळ रकमेचा हिशोब', backend: 'मिळालेली माहिती', total: 'एकूण निव्वळ', requested: 'सविस्तर हिशोब मागितला आहे', comparison: 'मंडी तुलना', received: 'मिळालेल्या क्रमाने', recommended: 'शिफारस', distance: 'अंतर उपलब्ध नाही', net: 'निव्वळ / क्विंटल', standing: 'विक्रीची योजना', watch: 'पाहा', currentTarget: 'सध्याचा भाव / लक्ष्य भाव', sellBy: 'विक्रीची शेवटची वेळ', fallback: 'पर्यायी कृती', nearest: 'जवळच्या मंडीत विका', change: 'हा सल्ला कधी बदलेल?', changeText: 'लक्ष्य भाव मिळाला, शेवटची तारीख आली किंवा धोका रडारने थांबण्याचा सल्ला बंद केला तर.', backendReason: 'मिळालेल्या माहितीनुसार', days: 'दिवस', trust: 'या सल्ल्यावर विश्वास का ठेवावा', trustSub: 'अंदाजाची तपासणी, परवानगी आणि धोका रडार', noBreakdown: 'फक्त एकूण रक्कम मिळाली आहे; सविस्तर हिशोब मागितला आहे.'
} : language === 'hi' ? {
  advice: 'सलाह कार्ड', typical: 'सामान्य शुद्ध राशि', likely: 'संभावित दायरा', confidence: 'भरोसा', measured: 'आज पास की मंडी में बेचने की तुलना', modal: 'मंडी का सामान्य भाव केवल संदर्भ है; पक्की मिलने वाली राशि नहीं।', breakdown: 'शुद्ध राशि का हिसाब', backend: 'मिली जानकारी', total: 'कुल शुद्ध राशि', requested: 'विस्तृत हिसाब मांगा गया है', comparison: 'मंडी तुलना', received: 'मिले क्रम में', recommended: 'सलाह', distance: 'दूरी उपलब्ध नहीं', net: 'शुद्ध / क्विंटल', standing: 'बिक्री योजना', watch: 'निगरानी', currentTarget: 'अभी का भाव / लक्ष्य भाव', sellBy: 'बेचने की आखिरी तारीख', fallback: 'दूसरा विकल्प', nearest: 'पास की मंडी में बेचें', change: 'यह सलाह कब बदलेगी?', changeText: 'लक्ष्य भाव मिले, आखिरी तारीख आए या जोखिम जांच रुकने की सलाह बंद करे।', backendReason: 'मिली जानकारी के अनुसार', days: 'दिन', trust: 'इस सलाह पर भरोसा क्यों करें', trustSub: 'अनुमान की जांच, अनुमति और जोखिम जांच', noBreakdown: 'सिर्फ कुल राशि मिली है; विस्तृत हिसाब मांगा गया है।'
} : {
  advice: 'Advice card', typical: 'Typical net', likely: 'Likely range', confidence: 'Confidence', measured: 'Measured against nearest sell-today option', modal: 'Modal price is a market-level reference, not a guaranteed realisation price.', breakdown: 'Net-return breakdown', backend: 'Backend values', total: 'Total net', requested: 'Breakdown requested from backend', comparison: 'Mandi comparison', received: 'Ranked as received', recommended: 'Recommended', distance: 'Distance unavailable', net: 'Net / q', standing: 'Standing order', watch: 'Watch', currentTarget: 'Current versus target', sellBy: 'Sell-by', fallback: 'Fallback', nearest: 'Sell at nearest mandi', change: 'What would change this advice', changeText: 'The target price is reached, the deadline arrives, or the shock radar suspends holds.', backendReason: 'Backend values', days: 'days', trust: 'Why you can trust this advice', trustSub: 'Calibration, gate status and shock radar', noBreakdown: 'Only the total was provided; a detailed breakdown was requested.'
};

export function AdviceCard({ reply, language = 'en' }: { reply: ChatReply; language?: Language }) {
  const copy = labels(language); const confidence = reply.confidence_label || 'NONE'; const status = statusLabel[reply.status || '']?.[language] || (language === 'mr' ? 'तपासा' : language === 'hi' ? 'जांचें' : 'Review');
  return <section className="bg-surface-container-lowest rounded-2xl border border-primary/25 shadow-[0_5px_20px_rgba(31,42,31,0.07)] p-4"><div className="flex items-center justify-between gap-3 mb-3"><div className="flex items-center gap-2 text-primary"><Sparkles size={16} /><span className="text-[11px] uppercase tracking-wider font-bold">{copy.advice}</span></div><span className="px-2 py-1 rounded-full bg-secondary-container text-on-secondary-container text-[10px] font-bold">{status}</span></div><h2 className="text-[17px] font-bold leading-snug text-on-surface">{reply.text.split(/[.!?]/)[0]}.</h2><div className="grid grid-cols-2 gap-2 mt-4"><div className="bg-surface-container-low rounded-xl p-3"><p className="text-[10px] text-on-surface-variant uppercase font-bold">{copy.typical}</p><p className="text-[21px] font-bold text-primary mt-1">{money(reply.typical_gain_median)}<span className="text-xs font-semibold"> / {language === 'en' ? 'q' : 'क्विंटल'}</span></p><p className="text-[11px] text-on-surface-variant">{copy.likely} {money(reply.likely_range_min)}–{money(reply.likely_range_max)}</p></div><div className="bg-surface-container-low rounded-xl p-3"><p className="text-[10px] text-on-surface-variant uppercase font-bold">{copy.confidence}</p><p className="text-[15px] font-bold mt-2 flex items-center gap-1.5"><ShieldCheck size={16} className={confidence === 'HIGH' ? 'text-secondary' : 'text-tertiary'} />{confidence === 'HIGH' ? (language === 'mr' ? 'जास्त' : language === 'hi' ? 'ज्यादा' : confidence) : confidence === 'MEDIUM' ? (language === 'mr' ? 'मध्यम' : language === 'hi' ? 'मध्यम' : confidence) : confidence}</p><p className="text-[11px] text-on-surface-variant mt-1">{copy.measured}</p></div></div><div className="flex items-start gap-2 mt-4 pt-3 border-t border-surface-container-high/60 text-[11px] text-on-surface-variant"><CircleHelp size={14} className="mt-0.5 shrink-0" /><span>{language === 'en' ? reply.modal_price_footer : copy.modal}</span></div></section>;
}

export function ReturnsAndMandis({ reply, language = 'en' }: { reply: ChatReply; language?: Language }) {
  const copy = labels(language); const options = reply.options_comparison || [];
  useEffect(() => { if (options.length && !(options[0] as any).breakdown) console.info('[BACKEND_REQUESTS] Option payload has total net only; request price, transport, fees, spoilage and storage breakdown.'); }, [options.length]);
  return <div className="space-y-4"><section className="bg-surface-container-lowest rounded-2xl border border-surface-container-high/70 p-4"><div className="flex items-center justify-between mb-3"><h3 className="font-bold text-[15px]">{copy.breakdown}</h3><span className="text-[10px] text-outline">{copy.backend}</span></div><div className="space-y-2">{options.map((option) => { const breakdown = (option as any).breakdown; return <div key={option.mandi_id} className="p-3 rounded-xl bg-surface-container-low"><div className="flex justify-between items-center"><span className="font-semibold text-xs">{option.mandi_name || option.mandi_id}</span>{option.is_nearest && <span className="text-[10px] px-1.5 py-0.5 rounded-full bg-secondary-container text-on-secondary-container font-bold">{copy.recommended}</span>}</div>{breakdown ? <div className="flex flex-wrap gap-1.5 mt-2 text-[10px] text-on-surface-variant">{['price','transport','fees','spoilage','storage','net'].map((key) => <span key={key} className="px-2 py-1 rounded bg-surface-container-lowest">{key}: {money(breakdown[key])}</span>)}</div> : <p className="mt-2 text-xs text-on-surface-variant">{copy.total}: <strong className="text-on-surface">{money(option.net_return_per_q)} / {language === 'en' ? 'q' : 'क्विंटल'}</strong></p>}</div>; })}</div></section><section className="bg-surface-container-lowest rounded-2xl border border-surface-container-high/70 p-4"><div className="flex items-center justify-between mb-3"><h3 className="font-bold text-[15px]">{copy.comparison}</h3><span className="text-[10px] text-outline">{copy.received}</span></div><div className="overflow-x-auto"><table className="w-full text-left text-xs"><thead className="text-[10px] uppercase text-outline"><tr><th className="pb-2">#</th><th className="pb-2">{language === 'mr' ? 'मंडी' : language === 'hi' ? 'मंडी' : 'Mandi'}</th><th className="pb-2 text-right">{copy.net}</th></tr></thead><tbody>{options.map((option, index) => <tr key={option.mandi_id} className="border-t border-surface-container-high/50"><td className="py-2 font-bold">{index + 1}</td><td className="py-2">{option.mandi_name || option.mandi_id}{option.distance_km ? <span className="block text-[10px] text-outline">{option.distance_km} km</span> : null}</td><td className="py-2 text-right font-bold text-primary">{money(option.net_return_per_q)}</td></tr>)}</tbody></table></div><MandiMap options={options} /></section></div>;
}

export function StandingOrder({ reply, language = 'en' }: { reply: ChatReply; language?: Language }) { const copy = labels(language); const trigger = reply.trigger_details; if (!trigger) return null; return <section className="bg-[#fff9eb] rounded-2xl border border-[#e7c87a] p-4"><div className="flex justify-between gap-3"><div><p className="text-[10px] uppercase tracking-wider font-bold text-tertiary">{copy.standing}</p><h3 className="font-bold text-[16px] mt-1">{copy.watch} {trigger.target_mandi_name || (language === 'mr' ? 'लक्ष्य मंडी' : language === 'hi' ? 'लक्ष्य मंडी' : 'target mandi')}</h3></div><span className="px-2 py-1 h-fit rounded-full bg-[#f7e4ac] text-[#775b19] text-[10px] font-bold">{language === 'mr' ? 'निगराणी' : language === 'hi' ? 'निगरानी' : 'WATCHING'}</span></div><div className="mt-4"><div className="flex justify-between text-xs"><span>{copy.currentTarget}</span><strong>{money(reply.options_comparison?.[1]?.projected_modal_price)} / {money(trigger.trigger_price)}</strong></div><div className="h-2 rounded-full bg-[#f0dfb0] mt-2 overflow-hidden"><div className="h-full bg-tertiary rounded-full" style={{ width: '72%' }} /></div></div><div className="grid grid-cols-2 gap-2 mt-4 text-xs"><div><span className="text-outline block">{copy.sellBy}</span><strong>{language === 'en' ? `Day ${trigger.exit_deadline_days}` : `${trigger.exit_deadline_days} ${copy.days}`}</strong></div><div><span className="text-outline block">{copy.fallback}</span><strong>{copy.nearest}</strong></div></div><p className="mt-3 text-xs text-on-surface-variant">{language === 'en' ? trigger.condition_description : (language === 'mr' ? `लासलगावचा भाव ${money(trigger.trigger_price)} प्रति क्विंटल झाला किंवा ${trigger.exit_deadline_days} दिवस पूर्ण झाले तर माल विका.` : `लासलगांव का भाव ${money(trigger.trigger_price)} प्रति क्विंटल हो या ${trigger.exit_deadline_days} दिन पूरे हों तो माल बेचें।`)}</p><div className="mt-3 pt-3 border-t border-[#e7c87a] text-xs"><p className="font-bold">{copy.change}</p><p className="mt-1 text-on-surface-variant">{copy.changeText}</p></div></section>; }

export const ChatsScreen: React.FC<ChatsScreenProps> = ({ language, onNavigate }) => {
  const [reply, setReply] = useState<ChatReply>(mockWaitWithTrigger); const [input, setInput] = useState(''); const [loading, setLoading] = useState(false); const [offline, setOffline] = useState(false); const [messages, setMessages] = useState<ChatMessage[]>([]); const copy = labels(language);
  const send = async (value = input) => { if (!value.trim() || loading) return; setInput(''); setLoading(true); setOffline(false); setMessages((items) => [...items, { id: String(Date.now()), sender: 'user', text: value, timestamp: 'Now' }]); try { const next = await api.sendChat({ session_id: reply.session_id, message: value, language, source: 'text' }); setReply(next); } catch { setOffline(true); } finally { setLoading(false); } };
  return <div className="flex flex-col w-full min-h-[calc(100vh-64px)] pb-24 pt-16 max-w-xl mx-auto px-margin"><div className="py-3 flex items-center gap-2"><Sparkles size={18} className="text-primary" /><strong>{copy.advice}</strong></div><div className="space-y-4"><AdviceCard reply={reply} language={language} /><ReturnsAndMandis reply={reply} language={language} />{reply.status === 'WAIT_WITH_TRIGGER' && <StandingOrder reply={reply} language={language} />}<button type="button" onClick={() => onNavigate('evidence')} className="w-full bg-surface-container-lowest border border-surface-container-high rounded-xl p-3 flex items-center justify-between text-left"><span><strong className="block text-xs">{copy.trust}</strong><span className="text-[11px] text-on-surface-variant">{copy.trustSub}</span></span><ChevronRight size={17} /></button></div><div className="mt-4"><div className="text-xs text-on-surface-variant mb-2">{messages.map((message) => <p key={message.id}>{message.text}</p>)}</div>{offline && <div className="p-3 rounded-xl bg-error-container text-on-error-container text-xs flex gap-2"><CloudOff size={15} />Offline</div>}<form onSubmit={(event) => { event.preventDefault(); send(); }} className="flex items-center gap-2 bg-surface-container-lowest p-2 rounded-2xl border border-surface-container-high"><button type="button" aria-label="Use microphone" className="w-9 h-9 rounded-xl bg-surface-container flex items-center justify-center text-primary"><Mic size={17} /></button><input value={input} onChange={(event) => setInput(event.target.value)} placeholder={language === 'mr' ? 'भाव किंवा व्यापाऱ्याची ऑफर लिहा' : language === 'hi' ? 'भाव या व्यापारी ऑफर लिखें' : 'Ask about price or offer'} className="flex-1 px-1 py-1 text-xs bg-transparent outline-none" /><button type="submit" aria-label="Send message" disabled={!input.trim() || loading} className="w-10 h-10 rounded-xl bg-primary text-on-primary flex items-center justify-center disabled:opacity-40"><Send size={17} /></button></form></div></div>;
};
