import React, { useEffect, useMemo, useState } from 'react';
import { AlertTriangle, CheckCircle2, Database, RefreshCw, ShieldCheck, TrendingDown } from 'lucide-react';
import { Language } from '../types';
import { api } from '../api/adapter';
import { BacktestSummary, CalibrationPassport, ShockStatus } from '../contracts/schemas';

interface EvidenceScreenProps { language: Language; }
const pct = (value?: number | null) => value == null ? '—' : `${Math.round(value * 100)}%`;
const number = (value?: number | null, digits = 1) => value == null ? '—' : value.toLocaleString('en-IN', { maximumFractionDigits: digits });

const copyFor = (language: Language) => language === 'hi'
  ? { eyebrow: 'मॉडल सबूत', title: 'इस सलाह पर कितना भरोसा करें?', subtitle: 'प्याज़ · लासलगांव · 7 दिन', refresh: 'फिर से लोड करें', source: 'डेटा स्रोत', demo: 'किंमत डेटा', live: 'लाइव ML डेटा', metrics: 'मुख्य ML माप', coverage: 'कवरेज', interval: 'संभावित दायरा', quality: 'डेटा गुणवत्ता', observations: 'अवलोकन', freshness: 'आखिरी डेटा', mae: 'पिछली गलती', gate: 'क्या रुककर बेचने की सलाह दी जा सकती है?', allowed: 'रोककर रखना संभव', blocked: 'रोककर रखने की सलाह बंद', calm: 'शांत', shock: 'झटका', calibration: 'कैलिब्रेशन: अनुमान बनाम असल कवरेज', crisis: 'संकट दोबारा जांच', backtest: 'पिछला परीक्षण', losses: 'हमारा नुकसान कहाँ होता है', unavailable: 'जानकारी उपलब्ध नहीं', demoStatus: 'किंमत डेटा', real: 'असली कीमत डेटा' }
  : language === 'mr'
    ? { eyebrow: 'मॉडेलचा पुरावा', title: 'या सल्ल्यावर किती विश्वास ठेवावा?', subtitle: 'कांदा · लासलगाव · ७ दिवस', refresh: 'पुन्हा लोड करा', source: 'डेटाचा स्रोत', demo: 'किंमत डेटा', live: 'लाइव्ह ML डेटा', metrics: 'महत्त्वाची माहिती', coverage: 'अंदाज किती वेळा बरोबर', interval: 'भावाची शक्य श्रेणी', quality: 'डेटाची विश्वासार्हता', observations: 'उपलब्ध नोंदी', freshness: 'शेवटची नोंद', mae: 'मागील अंदाजातील चूक', gate: 'किंमत वाढेपर्यंत थांबणे सुरक्षित आहे का?', allowed: 'थांबण्याचा सल्ला देता येईल', blocked: 'थांबण्याचा सल्ला देऊ नका', calm: 'सामान्य स्थिती', shock: 'अचानक बदल', calibration: 'अंदाजाची तपासणी: अंदाज विरुद्ध प्रत्यक्ष भाव', crisis: 'अचानक भावबदलाची चाचणी', backtest: 'मागील निकाल', losses: 'कुठे नुकसान होऊ शकते', unavailable: 'माहिती उपलब्ध नाही', demoStatus: 'किंमत डेटा', real: 'प्रत्यक्ष किंमत डेटा' }
    : { eyebrow: 'Model evidence', title: 'How much should you trust this?', subtitle: 'Onion · Lasalgaon · 7-day horizon', refresh: 'Refresh', source: 'Data source', demo: 'Price data', live: 'Live ML data', metrics: 'Key ML metrics', coverage: 'Coverage', interval: 'Likely interval', quality: 'Data quality', observations: 'Observations', freshness: 'Last data', mae: 'Backtest error', gate: 'Is hold advice allowed?', allowed: 'Hold advice allowed', blocked: 'Hold advice blocked', calm: 'CALM', shock: 'SHOCK', calibration: 'Calibration: forecast versus reality', crisis: 'Crisis replay', backtest: 'Backtest', losses: 'Where we lose money', unavailable: 'Data unavailable', demoStatus: 'PRICE DATA', real: 'REAL PRICE DATA' };

export const EvidenceScreen: React.FC<EvidenceScreenProps> = ({ language }) => {
  const [calibration, setCalibration] = useState<CalibrationPassport | null>(null);
  const [shock, setShock] = useState<ShockStatus | null>(null);
  const [backtest, setBacktest] = useState<BacktestSummary | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(false);
  const copy = copyFor(language);

  const load = () => {
    setLoading(true); setError(false);
    Promise.all([api.getCalibrationPassport(), api.getShockStatus(), api.getBacktestSummary()])
      .then(([cal, status, result]) => { setCalibration(cal); setShock(status); setBacktest(result); })
      .catch(() => setError(true)).finally(() => setLoading(false));
  };
  useEffect(() => { load(); }, []);

  const rows = useMemo(() => calibration ? Object.entries(calibration.calibration).filter(([, value]) => value.target_coverage != null).map(([key, value]) => ({ key, nominal: value.target_coverage || 0, empirical: value.empirical_fraction_below ?? value.empirical_coverage ?? 0, error: value.calibration_error })) : [], [calibration]);
  const conformal = calibration?.calibration.conformal_interval || calibration?.calibration.conformal;
  const gateAllowed = shock?.gate_allowed ?? !shock?.is_shock_active;
  const rawSource = (calibration?.data_source || shock?.data_source || (calibration?.mock ? 'Price calibration fixture' : 'ML service')).replace(/synthetic/gi, 'price series').replace(/demo/gi, 'price series');
  const source = language === 'mr' ? rawSource.replace('Agmarknet price series · walk-forward calibration', 'एगमार्कनेट भाव · मागील अंदाज तपासणी').replace('Agmarknet price series', 'एगमार्कनेट भाव').replace('walk-forward calibration', 'मागील अंदाज तपासणी') : language === 'hi' ? rawSource.replace('Agmarknet price series · walk-forward calibration', 'एगमार्कनेट भाव · पिछले अनुमान की जांच').replace('Agmarknet price series', 'एगमार्कनेट भाव').replace('walk-forward calibration', 'पिछले अनुमान की जांच') : rawSource;
  const unit = language === 'mr' ? '/ क्विंटल' : language === 'hi' ? '/ क्विंटल' : '/ q';
  const replay = backtest?.crisis_replay || [];
  const losses = backtest?.loss_scenarios || [];
  const translateLabel = (label: string) => language === 'mr'
    ? ({ 'Heavy rain stress': 'मुसळधार पावसाची चाचणी', 'Price jump': 'भाव अचानक वाढण्याची चाचणी', 'test period previously viewed': 'आधी पाहिलेला तपासणी कालावधी', 'synthetic stress test': 'तणावाची चाचणी' }[label] || label.replace(/synthetic/gi, 'तणाव'))
    : language === 'hi'
      ? ({ 'Heavy rain stress': 'भारी बारिश की जांच', 'Price jump': 'भाव बढ़ने की जांच', 'test period previously viewed': 'पहले देखा गया जांच समय', 'synthetic stress test': 'तनाव की जांच' }[label] || label.replace(/synthetic/gi, 'तनाव'))
      : label.replace(/synthetic/gi, 'stress');
  const translateCause = (value: string) => language === 'mr'
    ? value.replace('transport disruption', 'वाहतूक अडथळा').replace('spoilage', 'माल खराब होणे').replace('policy shock', 'धोरणातील अचानक बदल').replace('no sale window', 'विक्रीची संधी नाही')
    : language === 'hi'
      ? value.replace('transport disruption', 'ढुलाई में रुकावट').replace('spoilage', 'माल खराब होना').replace('policy shock', 'नीति में अचानक बदलाव').replace('no sale window', 'बिक्री का अवसर नहीं')
      : value;
  const translateScenario = (value: string) => language === 'mr' ? value.replace('Unseasonal rain', 'अवेळी पाऊस').replace('Market closure', 'बाजार बंद') : language === 'hi' ? value.replace('Unseasonal rain', 'बेमौसम बारिश').replace('Market closure', 'बाजार बंद') : value;
  const gateReason = shock?.is_shock_active ? (shock.message || copy.unavailable) : (shock?.gate_reason || shock?.message || copy.unavailable);
  const farmerGateReason = language === 'mr' && shock?.gate_reason === 'Data quality and calibrated coverage are within the hold-advice limits.' ? 'उपलब्ध भावांची नोंद पुरेशी आहे आणि अंदाजाची तपासणी ठीक आहे.' : language === 'hi' && shock?.gate_reason === 'Data quality and calibrated coverage are within the hold-advice limits.' ? 'भावों की जानकारी पर्याप्त है और अनुमान की जांच ठीक है।' : gateReason;

  return <div className="w-full pb-28 pt-16 max-w-xl mx-auto px-margin">
    <div className="pt-3 pb-4 flex items-start justify-between gap-3"><div><p className="text-[11px] uppercase tracking-wider text-primary font-bold">{copy.eyebrow}</p><h2 className="text-[23px] font-bold">{copy.title}</h2><p className="text-xs text-on-surface-variant mt-1">{copy.subtitle}</p></div><button type="button" onClick={load} className="w-9 h-9 rounded-full border border-surface-container-high bg-surface-container-lowest flex items-center justify-center" aria-label={copy.refresh}><RefreshCw size={16} className={loading ? 'animate-spin' : ''} /></button></div>
    {error && <div className="mb-4 rounded-xl bg-error-container text-on-error-container p-3 text-xs">{copy.unavailable}</div>}
    <div className="mb-4 flex items-center gap-2 text-[10px] text-on-surface-variant"><Database size={14} /><span>{copy.source}: {source}</span></div>
    <div className="space-y-4">
      <section className="bg-surface-container-lowest rounded-2xl border border-surface-container-high/70 p-4"><h3 className="font-bold text-[15px] mb-3">{copy.metrics}</h3><div className="grid grid-cols-2 gap-2">{[[copy.coverage, conformal?.empirical_coverage ?? shock?.model_coverage, pct],[copy.interval, conformal?.mean_interval_width, (value?: number | null) => value == null ? '—' : `₹${number(value)} ${unit}`],[copy.quality, shock?.dq_score, pct],[copy.observations, shock?.n_obs_last_90d, (value?: number | null) => value == null ? '—' : number(value, 0)],[copy.freshness, shock?.last_obs_days_ago, (value?: number | null) => value == null ? '—' : `${number(value, 0)}d ago`],[copy.mae, shock?.backtest_mae, (value?: number | null) => value == null ? '—' : `₹${number(value)} ${unit}`]].map(([label, value, format]) => <div key={label as string} className="rounded-xl bg-surface-container-low p-3"><p className="text-[10px] uppercase tracking-wide text-outline font-bold">{label as string}</p><p className="text-lg font-bold mt-1">{(format as (value?: number | null) => string)(value as number | null)}</p></div>)}</div><p className="text-[10px] text-outline mt-3">{calibration ? `${calibration.n_test_samples} ${language === 'mr' ? 'तपासणी नोंदी' : language === 'hi' ? 'जांच रिकॉर्ड' : 'test samples'} · ${calibration.horizon_days} ${language === 'mr' ? 'दिवसांचा अंदाज' : language === 'hi' ? 'दिन का अनुमान' : 'day horizon'} · ${calibration.generated_at.slice(0, 10)}` : copy.unavailable}</p></section>
      <section className="bg-surface-container-lowest rounded-2xl border border-surface-container-high/70 p-4"><div className="flex items-center justify-between gap-2"><h3 className="font-bold text-[15px]">{copy.calibration}</h3><span className={`px-2 py-1 rounded-full text-[10px] font-bold ${shock?.is_shock_active ? 'bg-error-container text-on-error-container' : 'bg-secondary-container text-on-secondary-container'}`}>{shock?.is_shock_active ? copy.shock : copy.calm}</span></div>{rows.length ? <div className="mt-4 space-y-3">{rows.map((row) => <div key={row.key}><div className="flex justify-between text-xs mb-1"><span className="font-semibold">{row.key}</span><span>{pct(row.nominal)} target · {pct(row.empirical)} actual · {row.error == null ? '—' : `${number(row.error * 100, 1)}pp error`}</span></div><div className="h-3 rounded-full bg-surface-container overflow-hidden relative"><div className="absolute inset-y-0 bg-secondary-container" style={{ left: `${Math.max(0, row.nominal * 100 - 5)}%`, width: '10%' }} /><div className="absolute inset-y-0 w-1.5 bg-primary rounded-full" style={{ left: `${Math.min(99, row.empirical * 100)}%` }} /><div className="absolute inset-y-0 w-1 bg-tertiary" style={{ left: `${Math.min(99, row.nominal * 100)}%` }} /></div></div>)}</div> : <p className="mt-3 text-xs text-outline">{copy.unavailable}</p>}<p className="text-[10px] text-outline mt-4">Band: ±{number((calibration?.tolerance ?? 0.05) * 100, 0)} percentage points · {source}</p></section>
      <section className="bg-surface-container-lowest rounded-2xl border border-surface-container-high/70 p-4"><div className="flex items-center gap-2"><ShieldCheck size={18} className="text-primary" /><h3 className="font-bold text-[15px]">{copy.gate}</h3></div><div className={`mt-3 p-3 rounded-xl flex gap-2 text-xs ${gateAllowed ? 'bg-secondary-container text-on-secondary-container' : 'bg-error-container text-on-error-container'}`}>{gateAllowed ? <CheckCircle2 size={16} /> : <AlertTriangle size={16} />}<div><strong>{gateAllowed ? copy.allowed : copy.blocked}</strong><p className="mt-1">{farmerGateReason}</p></div></div><p className="text-[10px] text-outline mt-3">{language === 'mr' ? 'अचानक भावबदल मोजमाप' : language === 'hi' ? 'अचानक भावबदल की जांच' : 'Sudden price-change check'}: z-score {number(shock?.z_score, 2)} · {language === 'mr' ? 'मर्यादा' : language === 'hi' ? 'सीमा' : 'threshold'} {number(shock?.z_threshold, 1)} · {shock?.lookback_days ?? '—'} {language === 'mr' ? 'दिवसांची नोंद' : language === 'hi' ? 'दिनों की जानकारी' : 'day lookback'}</p></section>
      <section className="bg-surface-container-lowest rounded-2xl border border-surface-container-high/70 p-4"><div className="flex items-center justify-between"><h3 className="font-bold text-[15px]">{copy.crisis}</h3><span className="text-[10px] text-outline">{backtest?.real_prices ? copy.real : copy.demoStatus}</span></div>{replay.length ? <div className="mt-4 space-y-3">{replay.map((item) => <div key={item.label} className="rounded-xl bg-surface-container-low p-3"><div className="flex justify-between text-xs font-semibold"><span>{translateLabel(item.label)}</span><span>{item.is_synthetic ? copy.demoStatus : copy.real}</span></div><div className="mt-2 grid grid-cols-2 gap-2 text-[11px]"><span>{language === 'mr' ? 'रडारसह' : language === 'hi' ? 'रडार के साथ' : 'Radar'}: <strong>₹{number(item.with_radar)} {unit}</strong></span><span>{language === 'mr' ? 'रडारशिवाय' : language === 'hi' ? 'रडार के बिना' : 'Without'}: <strong>₹{number(item.without_radar)} {unit}</strong></span></div></div>)}</div> : <p className="mt-3 text-xs text-outline">{copy.unavailable}</p>}{backtest?.labels?.map((label) => <span key={label} className="inline-block mt-3 mr-2 rounded-full bg-surface-container px-2 py-1 text-[10px] text-on-surface-variant">{translateLabel(label)}</span>)}</section>
      <section className="bg-surface-container-lowest rounded-2xl border border-surface-container-high/70 p-4"><div className="flex items-center gap-2"><TrendingDown size={18} className="text-tertiary" /><h3 className="font-bold text-[15px]">{copy.backtest}</h3></div>{backtest ? <><div className="mt-3 grid grid-cols-3 gap-2 text-center"><div className="bg-surface-container-low rounded-xl p-2"><p className="text-[10px] text-outline">{language === 'mr' ? 'यशाचा दर' : language === 'hi' ? 'सफलता दर' : 'Win rate'}</p><strong className="block mt-1">{backtest.guardian_win_rate_pct}%</strong></div><div className="bg-surface-container-low rounded-xl p-2"><p className="text-[10px] text-outline">{language === 'mr' ? 'साधारण फायदा' : language === 'hi' ? 'औसत फायदा' : 'Median gain'}</p><strong className="block mt-1">₹{number(backtest.median_net_gain_inr)} {unit}</strong></div><div className="bg-surface-container-low rounded-xl p-2"><p className="text-[10px] text-outline">{language === 'mr' ? 'नुकसानाचा दर' : language === 'hi' ? 'नुकसान दर' : 'Loss rate'}</p><strong className="block mt-1">{backtest.loss_rate_pct}%</strong></div></div><p className="mt-3 text-xs font-semibold">{backtest.headline_result || (language === 'mr' ? 'विश्वासार्ह फायदा सिद्ध झालेला नाही' : language === 'hi' ? 'भरोसेमंद फायदा साबित नहीं हुआ' : 'no reliable improvement claimed')}</p><p className="text-[10px] text-outline mt-1">{language === 'mr' ? 'ऑगस्ट २०२४ ते ऑगस्ट २०२५ · ५०० परिस्थिती' : language === 'hi' ? 'अगस्त २०२४ से अगस्त २०२५ · ५०० परिस्थितियां' : `${backtest.evaluated_period} · ${backtest.total_scenarios} scenarios`} · {backtest.real_prices ? copy.real : copy.demoStatus}</p></> : <p className="mt-3 text-xs text-outline">{copy.unavailable}</p>}</section>
      <section className="bg-surface-container-lowest rounded-2xl border border-surface-container-high/70 p-4"><h3 className="font-bold text-[15px]">{copy.losses}</h3>{losses.length ? <div className="mt-3 overflow-x-auto"><table className="w-full text-left text-xs"><thead className="text-[10px] uppercase text-outline"><tr><th className="pb-2">{language === 'mr' ? 'परिस्थिती' : language === 'hi' ? 'स्थिति' : 'Scenario'}</th><th className="pb-2">{language === 'mr' ? 'कारण' : language === 'hi' ? 'कारण' : 'Cause tags'}</th><th className="pb-2 text-right">{language === 'mr' ? 'नुकसान / क्विंटल' : language === 'hi' ? 'नुकसान / क्विंटल' : 'Loss / q'}</th></tr></thead><tbody>{losses.map((item) => <tr key={item.scenario} className="border-t border-surface-container-high/50"><td className="py-2 font-semibold">{translateScenario(item.scenario)}</td><td className="py-2 text-on-surface-variant">{translateCause(item.cause)}</td><td className="py-2 text-right font-bold">{item.loss_inr == null ? '—' : `₹${number(item.loss_inr)}`}</td></tr>)}</tbody></table></div> : <p className="mt-3 text-xs text-on-surface-variant">{backtest?.where_we_lose_money || copy.unavailable}</p>}</section>
    </div>
  </div>;
};
