import React from 'react';
import { ArrowRight, Leaf, ShieldCheck, TrendingUp } from 'lucide-react';
import { ASSETS } from '../data/mockData';
import { Language } from '../types';

interface LandingScreenProps { language: Language; onContinue: () => void; }

export const LandingScreen: React.FC<LandingScreenProps> = ({ language, onContinue }) => {
  const copy = language === 'mr' ? { title: 'शेतमालाला योग्य भाव', subtitle: 'भाव, हवामान आणि मंडीचा खर्च समजून योग्य वेळी विक्री करा.', start: 'सुरू करा', trusted: 'शेतकऱ्यांसाठी सोपा निर्णय साथी', crops: 'कांदा · टोमॅटो · सोयाबीन' } : language === 'hi' ? { title: 'फसल का सही भाव', subtitle: 'भाव, मौसम और मंडी का खर्च समझकर सही समय पर बेचें।', start: 'शुरू करें', trusted: 'किसानों के लिए आसान निर्णय साथी', crops: 'प्याज़ · टमाटर · सोयाबीन' } : { title: 'A fairer price for every harvest', subtitle: 'Understand prices, weather, and mandi costs before you decide when and where to sell.', start: 'Get started', trusted: 'A simple decision companion for farmers', crops: 'Onion · Tomato · Soybean' };
  return <main className="min-h-screen bg-surface flex flex-col"><div className="w-full max-w-xl mx-auto px-5 pt-8 flex-1"><div className="flex items-center gap-3"><img src={ASSETS.logo} alt="SHETBHAV" className="h-14 w-14 object-contain" /><div><p className="text-primary text-xs font-bold tracking-[0.16em]">SHETBHAV</p><p className="text-xs text-on-surface-variant">{copy.trusted}</p></div></div><section className="mt-8 relative overflow-hidden rounded-3xl bg-primary text-on-primary p-6 min-h-[390px] flex flex-col justify-end"><img src={ASSETS.onionSacksHero} alt="Fresh onions" className="absolute inset-0 w-full h-full object-cover opacity-35" /><div className="absolute inset-0 bg-gradient-to-t from-[#30412d] via-[#30412d]/55 to-transparent" /><div className="relative"><p className="text-xs text-secondary-fixed font-bold tracking-wide">{copy.crops}</p><h1 className="text-3xl font-bold leading-tight mt-2">{copy.title}</h1><p className="mt-3 text-sm text-primary-fixed leading-relaxed max-w-sm">{copy.subtitle}</p><button type="button" onClick={onContinue} className="mt-6 w-full rounded-xl bg-secondary-container text-on-secondary-container py-3.5 font-bold flex items-center justify-center gap-2">{copy.start}<ArrowRight size={18} /></button></div></section><div className="grid grid-cols-3 gap-2 mt-5 pb-8"><div className="bg-surface-container-lowest rounded-xl border border-surface-container-high p-3"><Leaf size={18} className="text-primary" /><p className="text-[11px] font-semibold mt-2">{language === 'mr' ? 'पिकाची अवस्था' : language === 'hi' ? 'फसल की हालत' : 'Crop condition'}</p></div><div className="bg-surface-container-lowest rounded-xl border border-surface-container-high p-3"><TrendingUp size={18} className="text-tertiary" /><p className="text-[11px] font-semibold mt-2">{language === 'mr' ? 'मंडी भाव' : language === 'hi' ? 'मंडी भाव' : 'Mandi prices'}</p></div><div className="bg-surface-container-lowest rounded-xl border border-surface-container-high p-3"><ShieldCheck size={18} className="text-secondary" /><p className="text-[11px] font-semibold mt-2">{language === 'mr' ? 'विश्वासाची माहिती' : language === 'hi' ? 'भरोसे की जानकारी' : 'Trusted signals'}</p></div></div></div></main>;
};
