import React, { useState } from 'react';
import { ArrowLeft, ArrowRight, Phone, UserRound } from 'lucide-react';
import { ASSETS } from '../data/mockData';
import { Language } from '../types';

interface LoginScreenProps { language: Language; onBack: () => void; onLogin: (name: string, phone: string) => void; }

export const LoginScreen: React.FC<LoginScreenProps> = ({ language, onBack, onLogin }) => {
  const [name, setName] = useState(''); const [phone, setPhone] = useState('');
  const copy = language === 'mr' ? { title: 'आपली माहिती द्या', subtitle: 'आपली शेतीची माहिती एका सोप्या ठिकाणी पाहा.', name: 'आपले नाव', phone: 'मोबाइल नंबर', continue: 'पुढे जा', back: 'मागे', note: 'आत्ता OTP ची गरज नाही.' } : language === 'hi' ? { title: 'अपनी जानकारी दें', subtitle: 'अपनी खेती की जानकारी एक आसान जगह पर देखें।', name: 'आपका नाम', phone: 'मोबाइल नंबर', continue: 'आगे बढ़ें', back: 'पीछे', note: 'अभी OTP की जरूरत नहीं है।' } : { title: 'Tell us about you', subtitle: 'Keep your farming decisions in one simple place.', name: 'Your name', phone: 'Mobile number', continue: 'Continue', back: 'Back', note: 'No OTP is needed for this demo.' };
  const submit = (event: React.FormEvent) => { event.preventDefault(); if (name.trim() && phone.trim().length >= 10) onLogin(name.trim(), phone.trim()); };
  return <main className="min-h-screen bg-surface flex flex-col"><div className="w-full max-w-xl mx-auto px-5 pt-8"><button type="button" onClick={onBack} className="w-10 h-10 rounded-full bg-surface-container flex items-center justify-center" aria-label={copy.back}><ArrowLeft size={18} /></button><div className="flex justify-center mt-5"><img src={ASSETS.logo} alt="SHETBHAV" className="h-24 w-24 object-contain" /></div><div className="mt-6"><p className="text-xs text-primary font-bold tracking-[0.16em]">SHETBHAV</p><h1 className="text-2xl font-bold mt-2">{copy.title}</h1><p className="text-sm text-on-surface-variant mt-2">{copy.subtitle}</p></div><form onSubmit={submit} className="mt-8 space-y-4"><label className="block"><span className="text-xs font-bold block mb-2">{copy.name}</span><span className="flex items-center gap-2 rounded-xl bg-surface-container-lowest border border-surface-container-high px-3"><UserRound size={18} className="text-outline" /><input value={name} onChange={(event) => setName(event.target.value)} className="w-full py-3 bg-transparent outline-none text-sm" required /></span></label><label className="block"><span className="text-xs font-bold block mb-2">{copy.phone}</span><span className="flex items-center gap-2 rounded-xl bg-surface-container-lowest border border-surface-container-high px-3"><Phone size={18} className="text-outline" /><input value={phone} onChange={(event) => setPhone(event.target.value.replace(/\D/g, '').slice(0, 10))} inputMode="numeric" className="w-full py-3 bg-transparent outline-none text-sm" required /></span></label><button type="submit" disabled={!name.trim() || phone.length < 10} className="w-full rounded-xl bg-primary text-on-primary py-3.5 font-bold flex items-center justify-center gap-2 disabled:opacity-40">{copy.continue}<ArrowRight size={18} /></button></form><p className="text-xs text-outline text-center mt-5">{copy.note}</p></div></main>;
};
