mandis:
- coverage_fraction: 1.0
  crop: soybean
  data_quality_score: 0.9953
  district: Dewas
  geocode_confidence: 0.4529793612120576
  geocode_source: nominatim
  lat: 22.96363
  lon: 76.054867
  longest_gap_days: 2
  mandi_id: madhy_dewas_dewas
  market_raw: Dewas
  needs_review: true
  state: Madhya Pradesh
- coverage_fraction: 1.0
  crop: soybean
  data_quality_score: 0.9944
  district: Damoh
  geocode_confidence: 0.348606766793213
  geocode_source: nominatim
  lat: 23.8360587
  lon: 79.4321389
  longest_gap_days: 3
  mandi_id: madhy_damoh_damoh
  market_raw: Damoh
  needs_review: true
  state: Madhya Pradesh
- coverage_fraction: 1.0
  crop: soybean
  data_quality_score: 0.9944
  district: Dewas
  geocode_confidence: 0.16004000076295108
  geocode_source: nominatim
  lat: 22.597517
  lon: 76.9166482
  longest_gap_days: 3
  mandi_id: madhy_dewas_khategaon
  market_raw: Khategaon
  needs_review: true
  state: Madhya Pradesh
- coverage_fraction: 1.0
  crop: soybean
  data_quality_score: 0.9944
  district: Hoshangabad
  geocode_confidence: 0.16005186312657357
  geocode_source: nominatim
  lat: 22.6124961
  lon: 77.762753
  longest_gap_days: 3
  mandi_id: madhy_hoshangabad_itarsi
  market_raw: Itarsi
  needs_review: true
  state: Madhya Pradesh
- coverage_fraction: 1.0
  crop: soybean
  data_quality_score: 0.9944
  district: Ujjain
  geocode_confidence: 0.95
  geocode_source: india_cities_latlng_csv
  lat: 23.1828
  lon: 75.7772
  longest_gap_days: 3
  mandi_id: madhy_ujjain_tarana
  market_raw: Tarana
  needs_review: false
  state: Madhya Pradesh
- coverage_fraction: 1.0
  crop: soybean
  data_quality_score: 0.9944
  district: Sagar
  geocode_confidence: 0.45706795194016775
  geocode_source: nominatim
  lat: 23.8417793
  lon: 78.7466817
  longest_gap_days: 3
  mandi_id: madhy_sagar_sagar
  market_raw: Sagar
  needs_review: true
  state: Madhya Pradesh
- coverage_fraction: 1.0
  crop: soybean
  data_quality_score: 0.9944
  district: Ratlam
  geocode_confidence: 0.95
  geocode_source: india_cities_latlng_csv
  lat: 23.3167
  lon: 75.0667
  longest_gap_days: 3
  mandi_id: madhy_ratlam_taal
  market_raw: Taal
  needs_review: false
  state: Madhya Pradesh
- coverage_fraction: 1.0
  crop: soybean
  data_quality_score: 0.9944
  district: Neemuch
  geocode_confidence: 0.16004000076295108
  geocode_source: nominatim
  lat: 24.4728129
  lon: 75.150867
  longest_gap_days: 3
  mandi_id: madhy_neemuch_manasa
  market_raw: Manasa
  needs_review: true
  state: Madhya Pradesh
- coverage_fraction: 1.0
  crop: soybean
  data_quality_score: 0.9944
  district: Khargone
  geocode_confidence: 0.37858398060478177
  geocode_source: nominatim
  lat: 21.825599
  lon: 75.614182
  longest_gap_days: 3
  mandi_id: madhy_khargone_khargone
  market_raw: Khargone
  needs_review: true
  state: Madhya Pradesh
- coverage_fraction: 1.0
  crop: soybean
  data_quality_score: 0.9944
  district: Khandwa
  geocode_confidence: 0.48809979373032214
  geocode_source: nominatim
  lat: 21.8203752
  lon: 76.3555424
  longest_gap_days: 3
  mandi_id: madhy_khandwa_khandwa
  market_raw: Khandwa
  needs_review: true
  state: Madhya Pradesh
- coverage_fraction: 1.0
  crop: soybean
  data_quality_score: 0.9944
  district: Indore
  geocode_confidence: 0.95
  geocode_source: india_cities_latlng_csv
  lat: 22.7206
  lon: 75.8472
  longest_gap_days: 3
  mandi_id: madhy_indore_sanwer
  market_raw: Sanwer
  needs_review: false
  state: Madhya Pradesh
- coverage_fraction: 1.0
  crop: soybean
  data_quality_score: 0.9944
  district: Ujjain
  geocode_confidence: 0.95
  geocode_source: india_cities_latlng_csv
  lat: 23.1828
  lon: 75.7772
  longest_gap_days: 3
  mandi_id: madhy_ujjain_khachrod
  market_raw: Khachrod
  needs_review: false
  state: Madhya Pradesh
- coverage_fraction: 1.0
  crop: soybean
  data_quality_score: 0.9933
  district: Harda
  geocode_confidence: 0.24004000076295107
  geocode_source: nominatim
  lat: 22.1534084
  lon: 76.8821612
  longest_gap_days: 3
  mandi_id: madhy_harda_khirakiya
  market_raw: Khirakiya
  needs_review: true
  state: Madhya Pradesh
- coverage_fraction: 1.0
  crop: soybean
  data_quality_score: 0.9932
  district: Shajapur
  geocode_confidence: 0.0
  geocode_source: failed
  lat: null
  lon: null
  longest_gap_days: 3
  mandi_id: madhy_shajapur_nalkehda
  market_raw: Nalkehda
  needs_review: true
  state: Madhya Pradesh
- coverage_fraction: 1.0
  crop: soybean
  data_quality_score: 0.993
  district: Mandsaur
  geocode_confidence: 0.16004000076295108
  geocode_source: nominatim
  lat: 24.2240391
  lon: 75.2684218
  longest_gap_days: 3
  mandi_id: madhy_mandsaur_piplya
  market_raw: Piplya
  needs_review: true
  state: Madhya Pradesh
- coverage_fraction: 1.0
  crop: onion
  data_quality_score: 0.9972
  district: Nashik
  geocode_confidence: 0.95
  geocode_source: india_cities_latlng_csv
  lat: 20.0
  lon: 73.7833
  longest_gap_days: 2
  mandi_id: mahar_nashik_lasalgaon
  market_raw: Lasalgaon
  needs_review: false
  state: Maharashtra
- coverage_fraction: 1.0
  crop: onion
  data_quality_score: 0.9972
  district: Pune
  geocode_confidence: 0.95
  geocode_source: india_cities_latlng_csv
  lat: 18.5196
  lon: 73.8553
  longest_gap_days: 2
  mandi_id: mahar_pune_manjri
  market_raw: Manjri
  needs_review: false
  state: Maharashtra
- coverage_fraction: 1.0
  crop: onion
  data_quality_score: 0.9972
  district: Nashik
  geocode_confidence: 0.95
  geocode_source: india_cities_latlng_csv
  lat: 20.0
  lon: 73.7833
  longest_gap_days: 2
  mandi_id: mahar_nashik_pimpalgaon
  market_raw: Pimpalgaon
  needs_review: false
  state: Maharashtra
- coverage_fraction: 1.0
  crop: onion
  data_quality_score: 0.9972
  district: Solapur
  geocode_confidence: 0.95
  geocode_source: india_cities_latlng_csv
  lat: 17.6833
  lon: 75.9167
  longest_gap_days: 2
  mandi_id: mahar_solapur_solapur
  market_raw: Solapur
  needs_review: false
  state: Maharashtra
- coverage_fraction: 1.0
  crop: onion
  data_quality_score: 0.9933
  district: Ahilyanagar
  geocode_confidence: 0.2636224323479305
  geocode_source: nominatim
  lat: 19.4031555
  lon: 74.6105605
  longest_gap_days: 2
  mandi_id: mahar_ahilyanagar_rahuri
  market_raw: Rahuri
  needs_review: true
  state: Maharashtra
- coverage_fraction: 1.0
  crop: tomato
  data_quality_score: 0.9972
  district: Ahilyanagar
  geocode_confidence: 0.26244239079806453
  geocode_source: nominatim
  lat: 19.4906351
  lon: 74.2466821
  longest_gap_days: 2
  mandi_id: mahar_ahilyanagar_sangamner
  market_raw: Sangamner
  needs_review: true
  state: Maharashtra
- coverage_fraction: 1.0
  crop: tomato
  data_quality_score: 0.9972
  district: Nagpur
  geocode_confidence: 0.95
  geocode_source: india_cities_latlng_csv
  lat: 21.1539
  lon: 79.0831
  longest_gap_days: 2
  mandi_id: mahar_nagpur_nagpur
  market_raw: Nagpur
  needs_review: false
  state: Maharashtra
- coverage_fraction: 1.0
  crop: tomato
  data_quality_score: 0.9972
  district: Nashik
  geocode_confidence: 0.95
  geocode_source: india_cities_latlng_csv
  lat: 20.0
  lon: 73.7833
  longest_gap_days: 2
  mandi_id: mahar_nashik_nashik
  market_raw: Nashik
  needs_review: false
  state: Maharashtra
- coverage_fraction: 1.0
  crop: tomato
  data_quality_score: 0.9972
  district: Pune
  geocode_confidence: 0.95
  geocode_source: india_cities_latlng_csv
  lat: 18.5196
  lon: 73.8553
  longest_gap_days: 2
  mandi_id: mahar_pune_pimpri
  market_raw: Pimpri
  needs_review: false
  state: Maharashtra
